import React, { useState } from "react";
import {
  Copy,
  Check,
  Edit3,
  Save,
  Download,
  RotateCcw,
  HelpCircle,
  Share2,
  BookOpen,
  Code,
  Terminal,
  Lightbulb,
  AlertTriangle,
  GraduationCap,
  ListChecks,
  ChevronDown,
  ChevronUp,
  FileText,
  ExternalLink,
} from "lucide-react";
import { NoteContent } from "../types";
import { downloadNotesAsPdf } from "../utils/exportPdf";
import { saveNote } from "../services/storage";

interface NotesOutputViewProps {
  note: NoteContent;
  onRegenerate: () => void;
  onGenerateQuizForTopic: (topic: string, subject: string) => void;
  onEditNote: (updatedNote: NoteContent) => void;
}

export const NotesOutputView: React.FC<NotesOutputViewProps> = ({
  note,
  onRegenerate,
  onGenerateQuizForTopic,
  onEditNote,
}) => {
  const [copied, setCopied] = useState(false);
  const [codeCopied, setCodeCopied] = useState(false);
  const [savedSuccess, setSavedSuccess] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);

  // Interactive MCQs practice states
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [showMCQExplanations, setShowMCQExplanations] = useState<Record<number, boolean>>({});

  // Accordion states for Viva & Exam Qs
  const [openVivaIndex, setOpenVivaIndex] = useState<Record<number, boolean>>({ 0: true });

  const handleCopyAll = () => {
    let fullText = `# ${note.topicTitle}\nSubject: ${note.subject} | Difficulty: ${note.difficulty || "Intermediate"}\n\n`;
    fullText += `## 1. Definition\n${note.definition}\n\n`;
    fullText += `## 2. Simple Explanation\n${note.simpleExplanation}\n\n`;
    fullText += `## 3. Detailed Explanation\n${note.detailedExplanation}\n\n`;
    fullText += `## 4. Why / Where It Is Used\n${note.whyWhereUsed}\n\n`;
    if (note.syntax) fullText += `## 5. Syntax\n\`\`\`\n${note.syntax}\n\`\`\`\n\n`;
    fullText += `## 6. Example\n${note.example}\n\n`;
    if (note.code) fullText += `## 7. Code\n\`\`\`\n${note.code}\n\`\`\`\n\n`;
    if (note.codeExplanation) fullText += `## 8. Code Explanation\n${note.codeExplanation}\n\n`;
    if (note.output) fullText += `## 9. Output\n\`\`\`\n${note.output}\n\`\`\`\n\n`;
    fullText += `## 10. Real-Life Example\n${note.realLifeExample}\n\n`;
    fullText += `## 11. Important Points\n${note.importantPoints.map((p) => `- ${p}`).join("\n")}\n\n`;
    fullText += `## 12. Common Mistakes\n${note.commonMistakes.map((m) => `- ${m}`).join("\n")}\n\n`;
    fullText += `## 13. Exam Questions\n### 2-Mark Questions:\n${note.examQuestions?.twoMarks?.map((q) => `- ${q}`).join("\n")}\n### 5-Mark Questions:\n${note.examQuestions?.fiveMarks?.map((q) => `- ${q}`).join("\n")}\n### 10-Mark Questions:\n${note.examQuestions?.tenMarks?.map((q) => `- ${q}`).join("\n")}\n\n`;
    fullText += `## 14. Viva Questions\n${note.vivaQuestions?.map((v, i) => `Q${i + 1}: ${v.question}\nA: ${v.answer}`).join("\n\n")}\n\n`;
    fullText += `## 15. MCQs\n${note.mcqs?.map((m, i) => `${i + 1}. ${m.question}\n${m.options.map((o, idx) => `   ${String.fromCharCode(65 + idx)}) ${o}`).join("\n")}\nCorrect: ${String.fromCharCode(65 + m.correctAnswer)} - ${m.explanation}`).join("\n\n")}`;

    navigator.clipboard.writeText(fullText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleCopyCode = () => {
    if (!note.code) return;
    navigator.clipboard.writeText(note.code);
    setCodeCopied(true);
    setTimeout(() => setCodeCopied(false), 2000);
  };

  const handleSaveNote = () => {
    saveNote(note);
    setSavedSuccess(true);
    setTimeout(() => setSavedSuccess(false), 2500);
  };

  const handleDownloadPdf = () => {
    downloadNotesAsPdf(note);
  };

  const handleShare = () => {
    const shareText = `Check out these exam notes on "${note.topicTitle}" for ${note.subject} generated by AI Notes Generator!`;
    if (navigator.share) {
      navigator
        .share({
          title: `${note.topicTitle} - Exam Notes`,
          text: shareText,
          url: window.location.href,
        })
        .catch(() => {
          navigator.clipboard.writeText(window.location.href);
          setShareSuccess(true);
          setTimeout(() => setShareSuccess(false), 2000);
        });
    } else {
      navigator.clipboard.writeText(`${shareText}\n\n${window.location.href}`);
      setShareSuccess(true);
      setTimeout(() => setShareSuccess(false), 2000);
    }
  };

  const handleSelectMCQ = (qIndex: number, optIndex: number) => {
    setSelectedAnswers((prev) => ({ ...prev, [qIndex]: optIndex }));
    setShowMCQExplanations((prev) => ({ ...prev, [qIndex]: true }));
  };

  const toggleViva = (idx: number) => {
    setOpenVivaIndex((prev) => ({ ...prev, [idx]: !prev[idx] }));
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      {/* Sticky Action Toolbar */}
      <div className="sticky top-16 z-30 bg-white/95 dark:bg-gray-900/95 backdrop-blur-md rounded-2xl border border-gray-200 dark:border-gray-800 p-3 sm:p-4 shadow-md transition-colors">
        <div className="flex flex-wrap items-center justify-between gap-2.5">
          {/* Note Title & Meta */}
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-blue-100 text-blue-800 dark:bg-blue-900/60 dark:text-blue-300">
                {note.subject}
              </span>
              <span className="text-xs text-gray-700 dark:text-gray-300 font-medium">
                {note.difficulty || "Intermediate"} • {note.noteType || "Exam Preparation"}
              </span>
            </div>
            <h2 className="text-base sm:text-xl font-extrabold text-gray-900 dark:text-white truncate">
              {note.topicTitle}
            </h2>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap items-center gap-1.5 sm:gap-2">
            {/* Copy */}
            <button
              id="action-copy-notes-btn"
              onClick={handleCopyAll}
              title="Copy notes to clipboard"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 text-xs font-semibold text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? "Copied!" : "Copy"}</span>
            </button>

            {/* Edit */}
            <button
              id="action-edit-notes-btn"
              onClick={() => onEditNote(note)}
              title="Edit notes content"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 text-xs font-semibold text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer"
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>Edit</span>
            </button>

            {/* Save */}
            <button
              id="action-save-notes-btn"
              onClick={handleSaveNote}
              title="Save to My Notes"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 text-xs font-semibold text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer"
            >
              {savedSuccess ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Save className="w-3.5 h-3.5" />}
              <span>{savedSuccess ? "Saved!" : "Save"}</span>
            </button>

            {/* Download PDF */}
            <button
              id="action-download-pdf-btn"
              onClick={handleDownloadPdf}
              title="Export as PDF document"
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-sm transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download PDF</span>
            </button>

            {/* Regenerate */}
            <button
              id="action-regenerate-btn"
              onClick={onRegenerate}
              title="Regenerate notes"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 text-xs font-semibold text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Regenerate</span>
            </button>

            {/* Generate Quiz */}
            <button
              id="action-quiz-from-note-btn"
              onClick={() => onGenerateQuizForTopic(note.topicTitle, note.subject)}
              title="Generate a 5-question test on this topic"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold shadow-sm transition-colors cursor-pointer"
            >
              <HelpCircle className="w-3.5 h-3.5" />
              <span>Generate Quiz</span>
            </button>

            {/* Share */}
            <button
              id="action-share-note-btn"
              onClick={handleShare}
              title="Share notes"
              className="p-1.5 rounded-lg border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 cursor-pointer"
            >
              <Share2 className="w-4 h-4" />
            </button>
          </div>
        </div>

        {shareSuccess && (
          <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-2">
            Link copied to clipboard for sharing!
          </p>
        )}
      </div>

      {/* Main Document Body - Pristine Academic Paper Aesthetic */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl shadow-lg p-6 sm:p-10 space-y-10 transition-colors">
        {/* Document Header Cover */}
        <div className="border-b border-gray-200 dark:border-gray-800 pb-8 space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-gray-700 dark:text-gray-300">
            <span className="font-semibold uppercase tracking-wider text-blue-600 dark:text-blue-400">
              AI Notes Generator • University Examination Series
            </span>
            <span>Date: {note.createdAt ? new Date(note.createdAt).toLocaleDateString() : new Date().toLocaleDateString()}</span>
          </div>

          <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 dark:text-white tracking-tight">
            {note.topicTitle}
          </h1>

          <div className="flex flex-wrap gap-2 text-xs font-medium">
            <span className="px-3 py-1 rounded-md bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-700">
              Subject: {note.subject}
            </span>
            <span className="px-3 py-1 rounded-md bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 border border-blue-200 dark:border-blue-900/50">
              Level: {note.difficulty || "Intermediate"}
            </span>
            <span className="px-3 py-1 rounded-md bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 border border-purple-200 dark:border-purple-900/50">
              Format: {note.noteType || "Exam Preparation"}
            </span>
          </div>
        </div>

        {/* SECTION 1: DEFINITION */}
        <section id="section-definition" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300 flex items-center justify-center font-bold text-xs">
              1
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Definition</h3>
          </div>
          <div className="p-4 rounded-xl bg-blue-50/70 dark:bg-blue-950/30 border border-blue-200/80 dark:border-blue-900/50">
            <p className="text-sm sm:text-base text-gray-800 dark:text-gray-200 font-medium leading-relaxed">
              {note.definition}
            </p>
          </div>
        </section>

        {/* SECTION 2: SIMPLE EXPLANATION */}
        <section id="section-simple-explanation" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300 flex items-center justify-center font-bold text-xs">
              2
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Simple Explanation</h3>
          </div>
          <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed pl-1">
            {note.simpleExplanation}
          </p>
        </section>

        {/* SECTION 3: DETAILED EXPLANATION */}
        <section id="section-detailed-explanation" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300 flex items-center justify-center font-bold text-xs">
              3
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Detailed Explanation</h3>
          </div>
          <div className="text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line pl-1">
            {note.detailedExplanation}
          </div>
        </section>

        {/* SECTION 4: WHY / WHERE IT IS USED */}
        <section id="section-why-where-used" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300 flex items-center justify-center font-bold text-xs">
              4
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Why / Where It Is Used</h3>
          </div>
          <div className="p-4 rounded-xl bg-emerald-50/50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/40 text-sm sm:text-base text-gray-800 dark:text-gray-200 leading-relaxed">
            {note.whyWhereUsed}
          </div>
        </section>

        {/* SECTION 5: SYNTAX */}
        {note.syntax && (
          <section id="section-syntax" className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 flex items-center justify-center font-bold text-xs">
                5
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Syntax & Notation</h3>
            </div>
            <div className="rounded-xl bg-gray-900 dark:bg-gray-950 border border-gray-800 p-4 font-mono text-sm text-cyan-300 overflow-x-auto">
              <pre>{note.syntax}</pre>
            </div>
          </section>
        )}

        {/* SECTION 6: EXAMPLE */}
        <section id="section-example" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300 flex items-center justify-center font-bold text-xs">
              6
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Example Scenario</h3>
          </div>
          <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed pl-1">
            {note.example}
          </p>
        </section>

        {/* SECTION 7: CODE */}
        {note.code && (
          <section id="section-code" className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg bg-gray-900 text-white dark:bg-gray-800 flex items-center justify-center font-bold text-xs">
                  7
                </div>
                <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Code Implementation</h3>
              </div>
              <button
                onClick={handleCopyCode}
                className="flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-mono bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors cursor-pointer"
              >
                {codeCopied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{codeCopied ? "Copied" : "Copy Code"}</span>
              </button>
            </div>
            <div className="rounded-xl bg-gray-950 border border-gray-800 p-4 font-mono text-xs sm:text-sm text-emerald-400 overflow-x-auto shadow-inner">
              <pre>{note.code}</pre>
            </div>
          </section>
        )}

        {/* SECTION 8: CODE EXPLANATION */}
        {note.codeExplanation && (
          <section id="section-code-explanation" className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 flex items-center justify-center font-bold text-xs">
                8
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Code Explanation</h3>
            </div>
            <div className="text-sm sm:text-base text-gray-700 dark:text-gray-300 leading-relaxed pl-1 whitespace-pre-line">
              {note.codeExplanation}
            </div>
          </section>
        )}

        {/* SECTION 9: OUTPUT */}
        {note.output && (
          <section id="section-output" className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-zinc-800 text-white flex items-center justify-center font-bold text-xs">
                9
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Expected Output</h3>
            </div>
            <div className="rounded-xl bg-gray-900 border border-gray-800 p-3.5 font-mono text-xs sm:text-sm text-yellow-300 overflow-x-auto flex items-start gap-2">
              <Terminal className="w-4 h-4 text-gray-500 shrink-0 mt-0.5" />
              <pre>{note.output}</pre>
            </div>
          </section>
        )}

        {/* SECTION 10: REAL-LIFE EXAMPLE */}
        <section id="section-real-life" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300 flex items-center justify-center font-bold text-xs">
              10
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">Real-Life Analogy</h3>
          </div>
          <div className="p-4 rounded-xl bg-amber-50/60 dark:bg-amber-950/20 border border-amber-200/70 dark:border-amber-900/40 text-sm sm:text-base text-gray-800 dark:text-gray-200 leading-relaxed flex items-start gap-3">
            <Lightbulb className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
            <div>{note.realLifeExample}</div>
          </div>
        </section>

        {/* SECTION 11: IMPORTANT POINTS */}
        <section id="section-important-points" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300 flex items-center justify-center font-bold text-xs">
              11
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
              Important Points (Revision Cheat Sheet)
            </h3>
          </div>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            {note.importantPoints.map((point, idx) => (
              <li
                key={idx}
                className="p-3 rounded-xl bg-blue-50/40 dark:bg-blue-950/20 border border-blue-100 dark:border-blue-900/40 text-xs sm:text-sm text-gray-800 dark:text-gray-200 flex items-start gap-2.5"
              >
                <span className="w-2 h-2 rounded-full bg-blue-600 dark:bg-blue-400 shrink-0 mt-1.5" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* SECTION 12: COMMON MISTAKES */}
        <section id="section-common-mistakes" className="space-y-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300 flex items-center justify-center font-bold text-xs">
              12
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
              Common Student Mistakes in Exams
            </h3>
          </div>
          <div className="space-y-2">
            {note.commonMistakes.map((mistake, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-rose-50/60 dark:bg-rose-950/20 border border-rose-200/70 dark:border-rose-900/40 flex items-start gap-3 text-xs sm:text-sm text-rose-950 dark:text-rose-200"
              >
                <AlertTriangle className="w-4 h-4 text-rose-600 dark:text-rose-400 shrink-0 mt-0.5" />
                <span>{mistake}</span>
              </div>
            ))}
          </div>
        </section>

        {/* SECTION 13: EXAM QUESTIONS */}
        <section id="section-exam-questions" className="space-y-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300 flex items-center justify-center font-bold text-xs">
              13
            </div>
            <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
              University Exam Questions
            </h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* 2 Marks */}
            <div className="rounded-2xl border border-gray-200 dark:border-gray-800 p-4 bg-gray-50/50 dark:bg-gray-800/40 space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-gray-200 dark:border-gray-700">
                <span className="font-bold text-sm text-blue-600 dark:text-blue-400">2-Mark Questions</span>
                <span className="text-[11px] px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300 font-semibold">
                  Short Answer
                </span>
              </div>
              <ul className="space-y-2 text-xs sm:text-sm text-gray-700 dark:text-gray-300">
                {note.examQuestions?.twoMarks?.map((q, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <span className="font-bold text-gray-400">{i + 1}.</span>
                    <span>{q}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* 5 Marks */}
            <div className="rounded-2xl border border-gray-200 dark:border-gray-800 p-4 bg-gray-50/50 dark:bg-gray-800/40 space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-gray-200 dark:border-gray-700">
                <span className="font-bold text-sm text-indigo-600 dark:text-indigo-400">5-Mark Questions</span>
                <span className="text-[11px] px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-300 font-semibold">
                  Descriptive
                </span>
              </div>
              <ul className="space-y-2 text-xs sm:text-sm text-gray-700 dark:text-gray-300">
                {note.examQuestions?.fiveMarks?.map((q, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <span className="font-bold text-gray-400">{i + 1}.</span>
                    <span>{q}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* 10 Marks */}
            <div className="rounded-2xl border border-gray-200 dark:border-gray-800 p-4 bg-gray-50/50 dark:bg-gray-800/40 space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-gray-200 dark:border-gray-700">
                <span className="font-bold text-sm text-purple-600 dark:text-purple-400">10-Mark Questions</span>
                <span className="text-[11px] px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300 font-semibold">
                  Essay / Comprehensive
                </span>
              </div>
              <ul className="space-y-2 text-xs sm:text-sm text-gray-700 dark:text-gray-300">
                {note.examQuestions?.tenMarks?.map((q, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <span className="font-bold text-gray-400">{i + 1}.</span>
                    <span>{q}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        {/* SECTION 14: VIVA QUESTIONS */}
        <section id="section-viva-questions" className="space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-teal-100 text-teal-700 dark:bg-teal-950 dark:text-teal-300 flex items-center justify-center font-bold text-xs">
                14
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
                Viva Voce Questions & Answers
              </h3>
            </div>
            <span className="text-xs text-gray-600 dark:text-gray-300">Click to reveal model answer</span>
          </div>

          <div className="space-y-2.5">
            {note.vivaQuestions?.map((item, idx) => {
              const isOpen = !!openVivaIndex[idx];
              return (
                <div
                  key={idx}
                  className="rounded-xl border border-gray-200 dark:border-gray-800 overflow-hidden bg-white dark:bg-gray-850 transition-all"
                >
                  <button
                    onClick={() => toggleViva(idx)}
                    className="w-full text-left p-3.5 flex items-center justify-between gap-3 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors cursor-pointer"
                  >
                    <div className="flex items-center gap-2.5">
                      <span className="text-xs font-bold text-blue-600 dark:text-blue-400">Q{idx + 1}:</span>
                      <span className="text-sm font-semibold text-gray-900 dark:text-white">
                        {item.question}
                      </span>
                    </div>
                    {isOpen ? (
                      <ChevronUp className="w-4 h-4 text-gray-400 shrink-0" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />
                    )}
                  </button>

                  {isOpen && (
                    <div className="px-4 pb-3.5 pt-1 border-t border-gray-100 dark:border-gray-800 bg-gray-50/60 dark:bg-gray-900/50 text-xs sm:text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
                      <span className="font-bold text-emerald-600 dark:text-emerald-400 mr-1.5">Viva Answer:</span>
                      {item.answer}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* SECTION 15: MCQS */}
        <section id="section-mcqs" className="space-y-4 pt-2">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-200 dark:border-gray-800 pb-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300 flex items-center justify-center font-bold text-xs">
                15
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-gray-900 dark:text-white">
                Multiple-Choice Questions (MCQs)
              </h3>
            </div>
            <button
              onClick={() => onGenerateQuizForTopic(note.topicTitle, note.subject)}
              className="text-xs font-semibold text-purple-600 dark:text-purple-400 hover:underline flex items-center gap-1"
            >
              Take as Full Interactive Quiz →
            </button>
          </div>

          <div className="space-y-4">
            {note.mcqs?.map((mcq, qIdx) => {
              const selected = selectedAnswers[qIdx];
              const isAnswered = selected !== undefined;
              return (
                <div
                  key={qIdx}
                  className="p-4 sm:p-5 rounded-2xl border border-gray-200 dark:border-gray-800 bg-gray-50/40 dark:bg-gray-800/30 space-y-3"
                >
                  <p className="font-semibold text-sm sm:text-base text-gray-900 dark:text-white">
                    <span className="text-blue-600 dark:text-blue-400 mr-2">{qIdx + 1}.</span>
                    {mcq.question}
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {mcq.options.map((opt, optIdx) => {
                      const letter = String.fromCharCode(65 + optIdx);
                      const isCorrect = optIdx === mcq.correctAnswer;
                      const isChosen = selected === optIdx;

                      let btnStyle = "border-gray-200 dark:border-gray-700 hover:border-gray-300 text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-900";
                      if (isAnswered) {
                        if (isCorrect) {
                          btnStyle = "border-emerald-500 bg-emerald-50 dark:bg-emerald-950/60 text-emerald-900 dark:text-emerald-200 font-semibold";
                        } else if (isChosen && !isCorrect) {
                          btnStyle = "border-rose-500 bg-rose-50 dark:bg-rose-950/60 text-rose-900 dark:text-rose-200";
                        }
                      }

                      return (
                        <button
                          key={optIdx}
                          onClick={() => handleSelectMCQ(qIdx, optIdx)}
                          className={`text-left p-3 rounded-xl border text-xs sm:text-sm flex items-center gap-2.5 transition-all cursor-pointer ${btnStyle}`}
                        >
                          <span className="w-5 h-5 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 flex items-center justify-center font-bold text-[11px] shrink-0">
                            {letter}
                          </span>
                          <span className="flex-1">{opt}</span>
                          {isAnswered && isCorrect && <Check className="w-4 h-4 text-emerald-600 shrink-0" />}
                        </button>
                      );
                    })}
                  </div>

                  {isAnswered && (
                    <div className="p-3 rounded-xl bg-blue-50 dark:bg-blue-950/40 border border-blue-100 dark:border-blue-900/50 text-xs text-blue-900 dark:text-blue-200 leading-relaxed">
                      <span className="font-bold">Explanation:</span> {mcq.explanation}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* Bottom Quick Quiz Prompt */}
        <div className="pt-6 border-t border-gray-200 dark:border-gray-800 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="space-y-1 text-center sm:text-left">
            <p className="text-sm font-bold text-gray-900 dark:text-white">Ready to test your memory?</p>
            <p className="text-xs text-gray-600 dark:text-gray-300">
              Take a quick 5-question AI quiz generated directly from these notes.
            </p>
          </div>
          <button
            onClick={() => onGenerateQuizForTopic(note.topicTitle, note.subject)}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs sm:text-sm font-semibold shadow-md shadow-purple-500/20 cursor-pointer"
          >
            <HelpCircle className="w-4 h-4" />
            <span>Take AI Quiz on This Topic</span>
          </button>
        </div>
      </div>
    </div>
  );
};
